package GUI;


import ArrayList.ClienteJuridicoList;
import ArrayList.ClienteNaturalList;
import Clases.Cliente;
import Clases.ClienteJuridico;
import Clases.ClienteNatural;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author kcofa
 */
public class RegistroClientes extends javax.swing.JFrame {

    ClienteNaturalList cnatural = new ClienteNaturalList();
    ClienteJuridicoList cjuridico = new ClienteJuridicoList();
            
    public RegistroClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Registro = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        NumCliente = new javax.swing.JLabel();
        txtNomIden = new javax.swing.JTextField();
        Nombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jlFecha = new javax.swing.JLabel();
        txtFCh = new javax.swing.JTextField();
        jlRs = new javax.swing.JLabel();
        txtRS = new javax.swing.JTextField();
        jlRuc = new javax.swing.JLabel();
        txtRuc = new javax.swing.JTextField();
        tel = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        direc = new javax.swing.JLabel();
        txtdirec = new javax.swing.JTextField();
        correo = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        btnListar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rbPersonaNatural = new javax.swing.JRadioButton();
        rbPersonaJuridica = new javax.swing.JRadioButton();
        RazónSocial1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnVolver = new javax.swing.JToggleButton();
        Registro1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientesNatural = new javax.swing.JTable();
        btnEliminarCN = new javax.swing.JButton();
        Registro2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientesJuridico = new javax.swing.JTable();
        btnEliminarCJ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Registro.setBackground(new java.awt.Color(204, 204, 255));
        Registro.setForeground(new java.awt.Color(96, 0, 160));
        Registro.setText("PERSONA JURIDICA");

        NumCliente.setText("Tipo de cliente:");

        Nombre.setText("Nombre de identificacion:");

        jlFecha.setText("Fecha de nacimiento:");

        jlRs.setText("Razón Social:");

        jlRuc.setText("RUC:");

        tel.setText("Teléfono:");

        direc.setText("Dirección:");

        correo.setText("Correo Electrónico:");

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre completo:");

        buttonGroup2.add(rbPersonaNatural);
        rbPersonaNatural.setText("Persona Natural");
        rbPersonaNatural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPersonaNaturalActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbPersonaJuridica);
        rbPersonaJuridica.setText("Persona Jurídica");
        rbPersonaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPersonaJuridicaActionPerformed(evt);
            }
        });

        RazónSocial1.setText("Codigo Cliente:");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(correo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(direc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlRuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlRs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NumCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                            .addComponent(RazónSocial1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(btnVolver)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbPersonaNatural)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbPersonaJuridica)
                                .addGap(11, 11, 11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNomIden)
                                    .addComponent(txtFCh)
                                    .addComponent(txtRS)
                                    .addComponent(txtRuc)
                                    .addComponent(txttelefono)
                                    .addComponent(txtdirec)
                                    .addComponent(txtcorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                    .addComponent(txtCodigo))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnListar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGuardar)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbPersonaNatural)
                    .addComponent(rbPersonaJuridica))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(txtNomIden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlFecha)
                    .addComponent(txtFCh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlRs)
                    .addComponent(txtRS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RazónSocial1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlRuc)
                    .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tel)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direc)
                    .addComponent(txtdirec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correo)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnListar)
                    .addComponent(btnVolver)))
        );

        Registro1.setBackground(new java.awt.Color(204, 204, 255));
        Registro1.setForeground(new java.awt.Color(96, 0, 160));
        Registro1.setText("REGISTRO DE CLIENTES");

        tblClientesNatural.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de Identificacion", "Nombre Completo", "Fecha de Nacimiento", "Codigo Cliente", "Telefono", "Direccion", "Correo Electronico"
            }
        ));
        jScrollPane1.setViewportView(tblClientesNatural);

        btnEliminarCN.setText("Eliminar Clientes Natural");
        btnEliminarCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCNActionPerformed(evt);
            }
        });

        Registro2.setBackground(new java.awt.Color(204, 204, 255));
        Registro2.setForeground(new java.awt.Color(96, 0, 160));
        Registro2.setText("PERSONA NATURAL");

        tblClientesJuridico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de Identificacion", "Nombre Completo", "Razon Social", "Codigo Cliente", "RUC", "Telefono", "Direccion", "Correo Electronico"
            }
        ));
        jScrollPane2.setViewportView(tblClientesJuridico);

        btnEliminarCJ.setText("Eliminar Clientes Juridicos");
        btnEliminarCJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCJActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Registro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarCN))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEliminarCJ)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(190, 190, 190)
                    .addComponent(Registro1)
                    .addContainerGap(758, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(489, Short.MAX_VALUE)
                    .addComponent(Registro2)
                    .addGap(474, 474, 474)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEliminarCN)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarCJ)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(Registro1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(478, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(Registro2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(468, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCNActionPerformed
       int selectedRow = tblClientesNatural.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Cliente Natural");
            return;
        }

        List<ClienteNatural> listaClienteNatural = cnatural.listar();
        ClienteNatural eEliminar = listaClienteNatural.get(selectedRow);

        cnatural.quitar(eEliminar);

        DefaultTableModel dtm = (DefaultTableModel) tblClientesNatural.getModel();
        dtm.removeRow(selectedRow);

        JOptionPane.showMessageDialog(this, "Cliente Natural eliminado.");
     
    }//GEN-LAST:event_btnEliminarCNActionPerformed

    private void btnEliminarCJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCJActionPerformed
        int selectedRow = tblClientesJuridico.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente Juridico");
            return;
        }

        List<ClienteJuridico> listaClienteJuridico = cjuridico.listar();
        ClienteJuridico eEliminarJ = listaClienteJuridico.get(selectedRow);

        cjuridico.quitar(eEliminarJ);

        DefaultTableModel dtm = (DefaultTableModel) tblClientesJuridico.getModel();
        dtm.removeRow(selectedRow);

        JOptionPane.showMessageDialog(this, "Cliente Juridico eliminado.");
    }//GEN-LAST:event_btnEliminarCJActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(rbPersonaNatural.isSelected()){
            ClienteNatural nuevoCliente = new ClienteNatural();
                nuevoCliente.setDocumentoIdentificacion(txtNomIden.getText());
                nuevoCliente.setNombre(txtNombre.getText());
                nuevoCliente.setFechaNacimiento(txtFCh.getText());
                nuevoCliente.setCodigoCliente(txtCodigo.getText());
                nuevoCliente.setTelefono(txttelefono.getText());
                nuevoCliente.setDireccion(txtdirec.getText());
                nuevoCliente.setEmail(txtcorreo.getText());
                
                JOptionPane.showMessageDialog(this, "Cliente Natural agregado.");
                
                cnatural.agregar(nuevoCliente);
                
       
        }else if(rbPersonaJuridica.isSelected()){
            ClienteJuridico nuevocj = new ClienteJuridico();
                nuevocj.setDocumentoIdentificacion(txtNomIden.getText());
                nuevocj.setNombre(txtNombre.getText());
                nuevocj.setRazonSocial(txtRS.getText());
                nuevocj.setCodigoCliente(txtCodigo.getText());
                nuevocj.setRUC(txtRuc.getText());
                nuevocj.setTelefono(txttelefono.getText());
                nuevocj.setDireccion(txtdirec.getText());
                nuevocj.setEmail(txtcorreo.getText());
                
                
                JOptionPane.showMessageDialog(this, "Cliente Juridico agregado.");
                
                cjuridico.agregar(nuevocj);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        if(rbPersonaNatural.isSelected()){
        DefaultTableModel dtm=(DefaultTableModel) tblClientesNatural.getModel();
                while(dtm.getRowCount() !=0)dtm.removeRow(0);
        
                for(ClienteNatural cn: cnatural.listar()){
                    Object[] rowData = {
                        cn.getDocumentoIdentificacion(),
                        cn.getNombre(),
                        cn.getFechaNacimiento(),
                        cn.getCodigoCliente(),
                        cn.getTelefono(),
                        cn.getDireccion(),
                        cn.getEmail()
                    };
                    dtm.addRow(rowData);
                }
                
            limpiarControles();
      }else if(rbPersonaJuridica.isSelected()){
        DefaultTableModel dtm=(DefaultTableModel) tblClientesJuridico.getModel();
                while(dtm.getRowCount() !=0)dtm.removeRow(0);
        
                for(ClienteJuridico cj: cjuridico.listar()){
                    Object[] rowData = {
                        cj.getDocumentoIdentificacion(),
                        cj.getNombre(),
                        cj.getRazonSocial(),
                        cj.getCodigoCliente(),
                        cj.getRUC(),
                        cj.getTelefono(),
                        cj.getDireccion(),
                        cj.getEmail()
                    };
                    dtm.addRow(rowData);
                } 
               limpiarControlesJ(); 
      }
    }//GEN-LAST:event_btnListarActionPerformed
    
    
    private void rbPersonaNaturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPersonaNaturalActionPerformed
        jlRs.setText("");
        jlRuc.setText("");
        jlFecha.setText("Fecha de nacimiento:");
        txtRS.setVisible(false);
        txtRuc.setVisible(false);
        txtFCh.setVisible(true);
    }//GEN-LAST:event_rbPersonaNaturalActionPerformed

    private void rbPersonaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPersonaJuridicaActionPerformed
        jlFecha.setText("");
        jlRs.setText("Razón Social:");
        jlRuc.setText("RUC:");
        txtFCh.setVisible(false);
        txtRS.setVisible(true);
        txtRuc.setVisible(true);
    }//GEN-LAST:event_rbPersonaJuridicaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Menu menuPrincipal = new Menu();
        menuPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed
    
    
    public void limpiarControles(){
        txtNomIden.setText("");
        txtNombre.setText("");
        txtFCh.setText("");
        txtCodigo.setText("");
        txttelefono.setText("");
        txtdirec.setText("");
        txtcorreo.setText("");
        buttonGroup2.clearSelection();   
    }
    
    public void limpiarControlesJ(){
        txtNomIden.setText("");
        txtNombre.setText("");
        txtRS.setText("");
        txtCodigo.setText("");
        txtRuc.setText("");
        txttelefono.setText("");
        txtdirec.setText("");
        txtcorreo.setText("");
        buttonGroup2.clearSelection();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel NumCliente;
    private javax.swing.JLabel RazónSocial1;
    private javax.swing.JLabel Registro;
    private javax.swing.JLabel Registro1;
    private javax.swing.JLabel Registro2;
    private javax.swing.JButton btnEliminarCJ;
    private javax.swing.JButton btnEliminarCN;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnListar;
    private javax.swing.JToggleButton btnVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel correo;
    private javax.swing.JLabel direc;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlFecha;
    private javax.swing.JLabel jlRs;
    private javax.swing.JLabel jlRuc;
    private javax.swing.JRadioButton rbPersonaJuridica;
    private javax.swing.JRadioButton rbPersonaNatural;
    private javax.swing.JTable tblClientesJuridico;
    private javax.swing.JTable tblClientesNatural;
    private javax.swing.JLabel tel;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtFCh;
    private javax.swing.JTextField txtNomIden;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRS;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdirec;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
